### PR TITLE
Exporter fixes

### PR DESCRIPTION
**Pull request by mrakitin**

### CODE REVIEW

**Review by jwlodek — APPROVED** [review]

**Comment by jwlodek** [comment]
Do we need to re-deploy the IOC?

**Comment by mrakitin** [comment]
Ah, let's redeploy the IOC actually as the `save_hdf5` function was touched, and it's a critical part of the IOC.
Good point and thanks for your prompt review, @jwlodek!

**Comment by mrakitin** [comment]
A note about the tests we don't run the tests in the CI which touch either hardware/real libca IOC or tiled. It's done on the collection machine while testing the code.

**Comment by jwlodek** [comment]
Right, that's why I thought we needed a re-deploy, since that function is part of the caproto IOC. Can I do the redeploy now or are the users using the device now?

**Pull request merged**
